### ISSUE TITLE
最后还是调用/system/xbin/su

### ISSUE THREAD

**Issue by wuzhenda** [wendal/android_su#2]
这是不是有点搞笑啊，如何之间替换掉su？

**Comment by wendal** [comment]
android 下的/system/bin/su 的作用相当于普通linux下的sudo

**Comment by wuzhenda** [comment]
我的意思是你没有直接编译出su文件，而是通过通过jni去调用了系统中的su，这恐怕不是我们预想要的吧。

**Comment by wendal** [comment]
我晕

这些代码的核心是setuid和setgid, 如果jni去调用,就会改变整个虚拟机的uid或gid,那是不可以接受的.

这个项目就是要生成一个su文件啊,放在/system/bin/su 并赋予6777权限, 使其允许其他程序无提示的地获得root权限

**Comment by wuzhenda** [comment]
这么说吧，如果系统中没有 /system/xbin/su ，你的代码根本没有用.
如果/system/xbin/su 是SuperUser等apk自带的，你的代码也未必有用.
你是编译出了一个su的文件但是还是依赖于别人的su,所以只能算是一个jni调用,也许用个bash脚本就搞定了。

**Comment by wendal** [comment]
拿真机看过了? 分析过SuperUser到底带什么没?

1. /system/xbin/su 是系统自带的,不是SuperUser带的. 我们用的开发板就带,原生的也有,但这个su里面有个判断,如果uid!=0就会exit.
2. 这里哪里有jni调用了? 哪行代码带jni.h了? 别总说啥jni调用,根本没有.
3. "也许用个bash脚本就搞定",那你倒是写个出来看看, ps, android上默认没有bash. 再说, 用什么语言实现那是你的事, 我这些代码就是这样用,有啥不可以的

**Comment by wuzhenda** [comment]
1.真正的android product手机出厂是不带su的.你们开发板既然带了su就应该把这个su直接替换掉。
2.你放个jni的文件夹，不是给java调用的吗,
3.android还默认不带su呢，你怎么不说，

**Comment by wendal** [comment]
无聊,我都用了几年了.
